import pandas as pd
from pathlib import Path

# ============================================================
# NUMT Pipeline v11 (Production - Single Command)
# ============================================================
# Architecture:
#   1. User provides a raw manifest (_raw.tsv) with tissue + CRAM paths
#      (generated by run_v11.sh before Snakemake starts — no Docker needed)
#   2. Snakemake handles EVERYTHING from there:
#      extract_insert_size ──┐
#                            ├──> run_dinumt_split → merge → final
#      split_bam ────────────┘
#   3. insert_size and split_bam run IN PARALLEL (both depend only on raw manifest)
#   4. run_dinumt_split waits for BOTH to complete
# ============================================================

configfile: "config_v11.yaml"

# Docker image for all rules (Snakemake 9+)
container: config.get("docker_image", "ztang301/all_dinumt:v1.2J")

DONORS = config["donors"]
BASE_INPUT_DIR = config["base_input_dir"]
METADATA_DIR = config["metadata_dir"]
OUTPUT_DIR = config["output_dir"]
LOG_DIR = config["log_dir"]
SCRIPTS_DIR = config["scripts_dir"]
REF_FASTA = config["ref_fasta"]

# Fixed dinumt paths
DINUMT_SCRIPT = config.get("dinumt_script",
    "/storage1/fs1/jin810/Active/testing/yung-chun/AI-develop/NUMT-dinumt-pipeline/Custom_Tools/dinumt_AllNumts.pl")
DINUMT_MASK = config.get("dinumt_mask",
    "/storage1/fs1/jin810/Active/testing/ztang/code/SMaHT/tissue_NUMTs/pipeline_scripts/dinumt/refNumts.38.bed")

# 24 primary chromosomes
CHROMOSOMES = [f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"]

# Create directories
Path(METADATA_DIR).mkdir(parents=True, exist_ok=True)
Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
Path(LOG_DIR).mkdir(parents=True, exist_ok=True)

wildcard_constraints:
    donor="[A-Z0-9]+",
    tissue="[^/]+",
    chrom="chr[0-9XY]+"

# ============================================================
# Read tissue list from raw manifest (exists before Snakemake starts)
# ============================================================
def get_tissues(wildcards):
    raw_tsv = f"{METADATA_DIR}/{wildcards.donor}_raw.tsv"
    if Path(raw_tsv).exists():
        df = pd.read_csv(raw_tsv, sep='\t')
        return df['TISSUE'].tolist()
    return []

# ============================================================
# Target rule
# ============================================================
rule all:
    input:
        expand(f"{METADATA_DIR}/{{donor}}_final.tsv", donor=DONORS)
    default_target: True

# ============================================================
# Stage 1: Extract insert size (per tissue, runs in Docker)
#   - Reads CRAM path from raw manifest
#   - Uses chr20 sub-sampling for speed (~30 seconds per tissue)
#   - Runs in PARALLEL with split_bam
# ============================================================
rule extract_insert_size:
    output:
        insert_txt = f"{METADATA_DIR}/{{donor}}_{{tissue}}_insert.txt"
    params:
        helper_script = f"{SCRIPTS_DIR}/call_insert_size.sh",
        raw_manifest = f"{METADATA_DIR}/{{donor}}_raw.tsv"
    log:
        f"{LOG_DIR}/{{donor}}_{{tissue}}_insert.log"
    resources:
        mem_mb = 4000
    shell:
        """
        export PATH=/opt/conda/bin:$PATH
        bash {params.helper_script} {wildcards.tissue} {params.raw_manifest} {output.insert_txt} > {log} 2>&1
        """

# ============================================================
# Stage 2: Split BAM by chromosome (per tissue × chrom)
#   - Reads CRAM path from raw manifest
#   - Runs in PARALLEL with extract_insert_size
# ============================================================
rule split_bam:
    output:
        bam = temp(f"{OUTPUT_DIR}/split_bams/{{donor}}/{{tissue}}/{{chrom}}.bam"),
        bai = temp(f"{OUTPUT_DIR}/split_bams/{{donor}}/{{tissue}}/{{chrom}}.bam.bai")
    log:
        f"{LOG_DIR}/{{donor}}_{{tissue}}_{{chrom}}_split.log"
    params:
        ref = REF_FASTA,
        raw_manifest = f"{METADATA_DIR}/{{donor}}_raw.tsv"
    threads: 4
    resources:
        mem_mb = 8000
    shell:
        """
        export PATH=/opt/conda/bin:$PATH

        # Extract BAM path for this tissue from raw manifest
        BAM_PATH=$(awk -F'\t' -v tissue="{wildcards.tissue}" '$2 == tissue {{print $3}}' {params.raw_manifest})

        # Split: chrN + chrM
        samtools view -@ {threads} -T {params.ref} -b "$BAM_PATH" {wildcards.chrom} chrM > {output.bam} 2> {log}
        samtools index -@ {threads} {output.bam} 2>> {log}
        """

# ============================================================
# Stage 3: Run dinumt per chromosome
#   - WAITS for both split_bam AND extract_insert_size
#   - Reads insert size from the per-tissue insert.txt file
# ============================================================
rule run_dinumt_split:
    input:
        bam = f"{OUTPUT_DIR}/split_bams/{{donor}}/{{tissue}}/{{chrom}}.bam",
        bai = f"{OUTPUT_DIR}/split_bams/{{donor}}/{{tissue}}/{{chrom}}.bam.bai",
        insert_txt = f"{METADATA_DIR}/{{donor}}_{{tissue}}_insert.txt"
    output:
        vcf = temp(f"{OUTPUT_DIR}/split_vcfs/{{donor}}/{{tissue}}/dinumt_{{chrom}}.vcf")
    params:
        script = DINUMT_SCRIPT,
        mask = DINUMT_MASK,
        ref = REF_FASTA,
        prefix = "{tissue}_{chrom}"
    resources:
        mem_mb = 16000
    log:
        f"{LOG_DIR}/{{donor}}_{{tissue}}_{{chrom}}_dinumt.log"
    shell:
        """
        export PATH=/opt/conda/bin:$PATH

        # Read insert size from the per-tissue file
        MEAN_INSERT=$(awk -F'\t' '{{print $2}}' {input.insert_txt})
        INSERT_SD=$(awk -F'\t' '{{print $3}}' {input.insert_txt})

        LEN_CLUSTER_INCLUDE=$(python3 -c "import math; print(int(math.ceil($MEAN_INSERT + 3 * $INSERT_SD)))")
        LEN_CLUSTER_LINK=$((2 * LEN_CLUSTER_INCLUDE))

        perl {params.script} \
            --mask_filename={params.mask} \
            --input_filename={input.bam} \
            --reference={params.ref} \
            --min_reads_cluster=1 \
            --include_mask \
            --len_cluster_include=$LEN_CLUSTER_INCLUDE \
            --len_cluster_link=$LEN_CLUSTER_LINK \
            --max_read_cov=250000000 \
            --output_filename={output.vcf} \
            --prefix={params.prefix} \
            --insert_size=$MEAN_INSERT \
            --ucsc \
            > {log} 2>&1
        """

# ============================================================
# Stage 4: Merge per-chromosome VCFs into one per tissue
# ============================================================
rule merge_vcfs:
    input:
        vcfs = expand(f"{OUTPUT_DIR}/split_vcfs/{{donor}}/{{tissue}}/dinumt_{{chrom}}.vcf",
                      chrom=CHROMOSOMES, allow_missing=True)
    output:
        merged_vcf = f"{OUTPUT_DIR}/dinumt/{{donor}}_fullBAM_AllNumts/{{tissue}}.vcf"
    resources:
        mem_mb = 4000
    log:
        f"{LOG_DIR}/{{donor}}_{{tissue}}_merge.log"
    shell:
        """
        # Get header from the first VCF
        FIRST_VCF=$(echo "{input.vcfs}" | awk '{{print $1}}')
        grep "^#" "$FIRST_VCF" > {output.merged_vcf}

        # Append all data lines sorted by chromosome and position
        grep -h -v "^#" {input.vcfs} | sort -k1,1 -k2,2n >> {output.merged_vcf} || true

        echo "Merged VCF created: {output.merged_vcf}" > {log}
        """

# ============================================================
# Stage 5: Build final report
#   - Count NUMTs from each VCF
#   - Combine with raw manifest + insert sizes → final.tsv
# ============================================================
rule build_final_report:
    input:
        vcfs = lambda wc: expand(f"{OUTPUT_DIR}/dinumt/{{donor}}_fullBAM_AllNumts/{{tissue}}.vcf",
                                donor=wc.donor,
                                tissue=get_tissues(wc)),
        insert_files = lambda wc: expand(f"{METADATA_DIR}/{{donor}}_{{tissue}}_insert.txt",
                                         donor=wc.donor,
                                         tissue=get_tissues(wc))
    output:
        final_tsv = f"{METADATA_DIR}/{{donor}}_final.tsv"
    params:
        raw_manifest = f"{METADATA_DIR}/{{donor}}_raw.tsv",
        vcf_dir = f"{OUTPUT_DIR}/dinumt/{{donor}}_fullBAM_AllNumts"
    resources:
        mem_mb = 4000
    log:
        f"{LOG_DIR}/{{donor}}_build_final.log"
    run:
        import pandas as pd
        import os

        # Read raw manifest
        df = pd.read_csv(params.raw_manifest, sep='\t')
        
        # Ensure column types to avoid pandas strict dtype errors when assigning
        if 'DINUMT_VCF' in df.columns:
            df['DINUMT_VCF'] = df['DINUMT_VCF'].astype(str)

        # Fill in insert sizes from per-tissue files
        for idx, row in df.iterrows():
            tissue = row['TISSUE']
            insert_file = f"{METADATA_DIR}/{wildcards.donor}_{tissue}_insert.txt"
            if os.path.exists(insert_file):
                with open(insert_file) as f:
                    parts = f.read().strip().split('\t')
                    if len(parts) >= 3:
                        df.at[idx, 'MEAN_INSERT_SIZE'] = float(parts[1])
                        df.at[idx, 'INSERT_SIZE_SD'] = float(parts[2])

        # Fill in VCF paths and counts
        for idx, row in df.iterrows():
            tissue = row['TISSUE']
            vcf_path = f"{params.vcf_dir}/{tissue}.vcf"
            df.at[idx, 'DINUMT_VCF'] = vcf_path
            if os.path.exists(vcf_path):
                with open(vcf_path) as f:
                    count = sum(1 for line in f if not line.startswith('#'))
                df.at[idx, 'RAW_COUNTS'] = count
            else:
                df.at[idx, 'RAW_COUNTS'] = 0

        df.to_csv(output.final_tsv, sep='\t', index=False)

        with open(str(log), 'w') as logf:
            logf.write(f"Final report: {len(df)} tissues\n")
            logf.write(f"Output: {output.final_tsv}\n")
